services:
  app:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
        PORT: ${PORT}
    env_file: '.env'
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: production-local
    restart: on-failure
    network_mode: host # if database is in localhost
