services:
  app:
    container_name: expedients-app
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
        APP_PORT: ${APP_PORT}
    env_file: '.env'
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      NODE_ENV: production-local
    network_mode: host # if database is in localhost
